# Generated by Django 5.1.3 on 2024-11-15 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='festival',
            name='image',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='travel_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.traveldestination'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.festival'),
        ),
        migrations.AlterField(
            model_name='traveldestination',
            name='description',
            field=models.TextField(default='정보가 없습니다.'),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='created_at',
        ),
    ]
