# Generated by Django 5.1.3 on 2024-11-15 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_bookmark_unique_together_remove_festival_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'festival')},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='festival',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='festival_images/'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.festival'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traveldestination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='travel_destination',
        ),
    ]
